Repository COMP3005A-Project/bookstore, pull requests merged in 2021-11, with the labels that each got.

#22 Creating models, services, and repositories
  project/src/main/java/ca/bookstore3005/project/models/BankAccount.java
  project/src/main/java/ca/bookstore3005/project/models/BookOrder.java
  project/src/main/java/ca/bookstore3005/project/models/BooksInOrder.java
  project/src/main/java/ca/bookstore3005/project/models/Customer.java
  project/src/main/java/ca/bookstore3005/project/models/Publisher.java
  project/src/main/java/ca/bookstore3005/project/repositories/BankAccountRepository.java
  project/src/main/java/ca/bookstore3005/project/repositories/BookOrderRepository.java
  project/src/main/java/ca/bookstore3005/project/repositories/BooksInOrderRepository.java
  project/src/main/java/ca/bookstore3005/project/repositories/CustomerRepository.java
  project/src/main/java/ca/bookstore3005/project/repositories/PublisherRepository.java
  project/src/main/java/ca/bookstore3005/project/services/BankAccountService.java
  project/src/main/java/ca/bookstore3005/project/services/CustomerService.java
  project/src/main/java/ca/bookstore3005/project/services/PublisherService.java
Labels: backend

#32 Cart functionality
  project/src/main/java/ca/bookstore3005/project/controllers/BookController.java
  project/src/main/java/ca/bookstore3005/project/controllers/CheckoutController.java
  project/src/main/java/ca/bookstore3005/project/controllers/CustomerController.java
  project/src/main/java/ca/bookstore3005/project/models/IsbnPacket.java
  project/src/main/resources/data.sql
  project/src/main/resources/static/js/booksDT.js
  project/src/main/resources/templates/books.html
  project/src/main/resources/templates/fragments/header.html
  project/src/main/resources/templates/fragments/scripts.html
Labels: backend

#34 Registration Page
  project/pom.xml
  project/src/main/java/ca/bookstore3005/project/controllers/CustomerController.java
  project/src/main/java/ca/bookstore3005/project/models/Customer.java
  project/src/main/java/ca/bookstore3005/project/repositories/CustomerRepository.java
  project/src/main/java/ca/bookstore3005/project/services/CustomerService.java
  project/src/main/resources/schema.sql
  project/src/main/resources/templates/login.html
  project/src/main/resources/templates/registration.html
Labels: frontend, backend

#37 Feature/order functionality
  project/src/main/java/ca/bookstore3005/project/controllers/CheckoutController.java
  project/src/main/java/ca/bookstore3005/project/controllers/CustomerController.java
  project/src/main/java/ca/bookstore3005/project/controllers/OrderController.java
  project/src/main/java/ca/bookstore3005/project/models/Order.java
  project/src/main/java/ca/bookstore3005/project/repositories/OrderRepository.java
  project/src/main/java/ca/bookstore3005/project/services/BookService.java
  project/src/main/java/ca/bookstore3005/project/services/OrderService.java
  project/src/main/resources/schema.sql
  project/src/main/resources/static/js/checkout.js
  project/src/main/resources/templates/cart.html
  project/src/main/resources/templates/checkout.html
  project/src/main/resources/templates/fragments/header.html
  project/src/main/resources/templates/invalid_action.html
  project/src/main/resources/templates/order.html
  project/src/main/resources/templates/orders.html
Labels: frontend, backend

#44 Feature/checkout address
  project/src/main/java/ca/bookstore3005/project/controllers/CheckoutController.java
  project/src/main/java/ca/bookstore3005/project/controllers/OrderController.java
  project/src/main/java/ca/bookstore3005/project/models/Order.java
  project/src/main/java/ca/bookstore3005/project/repositories/OrderRepository.java
  project/src/main/java/ca/bookstore3005/project/services/OrderService.java
  project/src/main/resources/data.sql
  project/src/main/resources/schema.sql
  project/src/main/resources/templates/checkout.html
  project/src/main/resources/templates/order.html
Labels: frontend, backend

#61 Region entity 59
  README.md
  project/src/main/java/ca/bookstore3005/project/controllers/CustomerController.java
  project/src/main/java/ca/bookstore3005/project/models/Region.java
  project/src/main/java/ca/bookstore3005/project/repositories/OrderRepository.java
  project/src/main/java/ca/bookstore3005/project/repositories/RegionRepository.java
  project/src/main/java/ca/bookstore3005/project/services/OrderService.java
  project/src/main/java/ca/bookstore3005/project/services/RegionService.java
  project/src/main/resources/data.sql
  project/src/main/resources/schema.sql
Labels: backend, Database
